server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edusystem?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.example.dao.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true